name: Template check
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version: '1.27.1'
      - uses: tplAIter/tplaiter/.github/actions/template-check@12cf8f810faa25f8c573dcc22fbebb45b1c4db8c
